sudo: required
services:
  - docker

before_install:
  - docker build -t hiranokuosaka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hiranokuosaka/react-test npm run test

after_success:
  - docker build -t hiranokuosaka/multi-client ./client
  - docker build -t hiranokuosaka/multi-nginx ./nginx
  - docker build -t hiranokuosaka/multi-server ./server
  - docker build -t hiranokuosaka/multi-worker ./worker
