sudo: required
services:
  - docker

before_install:
  - docker build -t hiranokuosaka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hiranokuosaka/react-test npm run test

after_success:
  - docker build -t hiranokuosaka/multi-client ./client
  - docker build -t hiranokuosaka/multi-nginx ./nginx
  - docker build -t hiranokuosaka/multi-server ./server
  - docker build -t hiranokuosaka/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push hiranokuosaka/multi-client
  - docker push hiranokuosaka/multi-nginx
  - docker push hiranokuosaka/multi-server
  - docker push hiranokuosaka/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ca-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ca-central-1-106351276515
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
